// ============================================================
// FOLDER: 5. Project Delivery
// Purpose: Project portfolio metrics and individual project
//          progress for the Project Delivery Status panel.
// ============================================================

MEASURE _Measures[Total Projects] =
COUNTROWS(PROJECTS_TRACKER)
FORMAT STRING = "0"

MEASURE _Measures[Projects On Track] =
COUNTROWS(FILTER(PROJECTS_TRACKER, PROJECTS_TRACKER[Status] = "On Track"))
FORMAT STRING = "0"

MEASURE _Measures[Projects At Risk] =
COUNTROWS(FILTER(PROJECTS_TRACKER, PROJECTS_TRACKER[Status] IN {"At Risk", "Delayed"}))
FORMAT STRING = "0"

MEASURE _Measures[Projects Delayed] =
COUNTROWS(FILTER(PROJECTS_TRACKER, PROJECTS_TRACKER[Status] = "Delayed"))
FORMAT STRING = "0"

MEASURE _Measures[Projects In Progress] =
COUNTROWS(FILTER(PROJECTS_TRACKER, PROJECTS_TRACKER[Status] = "In Progress"))
FORMAT STRING = "0"

MEASURE _Measures[High Risk Projects] =
COUNTROWS(FILTER(PROJECTS_TRACKER, PROJECTS_TRACKER[Risk] = "High"))
FORMAT STRING = "0"

// Average across all projects — drives the portfolio progress ring.
MEASURE _Measures[Avg Project Progress] =
DIVIDE(AVERAGEX(PROJECTS_TRACKER, PROJECTS_TRACKER[Progress]), 100)
FORMAT STRING = "0.0%"

// Returns progress % for whichever project is selected in a slicer/filter.
// Used to populate individual project progress bars.
MEASURE _Measures[Selected Project Progress] =
DIVIDE(SELECTEDVALUE(PROJECTS_TRACKER[Progress], 0), 100)
FORMAT STRING = "0.0%"
